package com.netxs.Zewar;


public interface Default {

	String INVENTORY_VENDOR_STOCK_ISSUE_VOUCHER_PREFIX = "VI";
	String INVENTORY_VENDOR_STOCK_RETURN_VOUCHER_PREFIX = "VR";
	String INVENTORY_PURCHASE_METAL_VOUCHER_PREFIX = "PM";
	String INVENTORY_PURCHASE_GEM_VOUCHER_PREFIX = "PG";
	String INVENTORY_PURCHASE_JEWELLERY_VOUCHER_PREFIX = "PJ";
	String INVENTORY_SALES_VOUCHER_PREFIX = "SI";
	String CASH_BOOK_RECEIVE_VOUCHER_PREFIX = "CR";
	String CASH_BOOK_PAYMENT_VOUCHER_PREFIX = "CP";
	String SALES_INVOICE_VOUCHER_PREFIX = "SL";
	String SALES_ORDER_PREFIX = "SO";
	String SALES_ORDER_CANCELLATION_VOUCHER_PREFIX = "SC";
	String GENERAL_VOUCHER_PREFIX = "JV";
	
	int LEDGER_CASH_ACCOUNT_ID = 263;
	int PURCHASE_IN_ACCOUNT_ID = 268;	// Purchase / Stock In
	int PURCHASE_OUT_ACCOUNT_ID = 269; 	// Purchase Return / Stock Out 
	int SALES_OUT_ACCOUNT_ID = 266;		// Sales / Stock Out
	int SALES_IN_ACCOUNT_ID = 267;		// Sales Return / Stock In
	int LABOUR_EXPENSE_ACCOUNT_ID = 345;
	
	byte STOCK_TYPE_COMPANY = 1;
	byte STOCK_TYPE_CUSTOMER = 2;
	byte STOCK_TYPE_VENDOR = 3;
	byte WASTAGE_IN_PERCENTAGE = 1;
	byte WASTAGE_IN_RAATI = 2;
	byte VALUE_CALCULATE_BY_QUANTITY = 1;
	byte VALUE_CALCULATE_BY_WEIGHT = 2;
	byte WEIGHT_IN_GRAM = 1;
	byte WEIGHT_IN_CARAT = 2;
	byte VENDOR_PROCESS_BODY_MAKING = 1;
	byte VENDOR_PROCESS_STONE_SETTING = 2;
	
	byte SALES_ORDER_STATUS_PENDING = 1;
	byte SALES_ORDER_STATUS_PROCESS = 2;
	byte SALES_ORDER_STATUS_COMPLETE = 3;
	byte SALES_ORDER_STATUS_CANCEL = 4;

	byte SALES_ORDER_PROCESS_STATUS_PROCESS = 1;
	byte SALES_ORDER_PROCESS_STATUS_COMPLETE = 2;
	byte SALES_ORDER_PROCESS_STATUS_CANCEL = 3;

	char SALES_ORDER_CLONE_TYPE_NEW = 'N';
	char SALES_ORDER_CLONE_TYPE_COPY = 'C';
	char SALES_ORDER_CLONE_TYPE_REOPEN= 'R';
	
	byte CUSTOMER_INVENTORY_RETURN = 1;
	byte CUSTOMER_INVENTORY_KEEP_ADVANCE = 2;
	byte CUSTOMER_INVENTORY_PURCHASE = 3;
	byte CUSTOMER_INVENTORY_REPLACEMENT = 4;
}
